<?php

/**
 * @file
 * Contains dom_test.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dom_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dom_test module.
    case 'help.page.dom_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test PHP DOM manipulation.') . '</p>';
      return $output;

    default:
  }
}
