<?php

/**
 * @file
 * Contains dogs.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dogs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dogs module.
    case 'help.page.dogs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is about dogs.') . '</p>';
      return $output;

    default:
  }
}
